title: Yasuto Soma(@umasoya)
email: umasoya.0331+resume@google.com
baseurl: "/resume" # the subpath of your site, e.g. /blog
url: "https://umasoya.me" # the base hostname & protocol for your site, e.g. http://example.com
github_username: umasoya

#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - README.md
  - node_modules/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
